web/config/routes.rb
RailsBootstrap::Application.routes.draw do
  ### Maybe have graphs here?
  root :to => 'explorer#search'

  ### List of all machines or graphs?
  get 'explorer' => "explorer#explorer"

  ### Machines/ISV/OEM views
  get 'explorer/products/:vendor' => "explorer#products"
  get 'explorer/vendors' => "explorer#vendors"
  get 'explorer/objects' => "explorer#objects"
  get 'explorer/vendor/:name' => "explorer#vendor"
  get 'explorer/machine/:id' => "explorer#machine"

  ### Object views
  get 'explorer/uefi/:id' => "explorer#uefi"
  get 'explorer/firmware/:id' => "explorer#firmware"

  ### Downloads
  get 'explorer/file/:firmware_id/:id' => "explorer#file"
  get 'explorer/raw/:firmware_id/:id' => "explorer#raw"
  get 'explorer/download/:object_id' => "explorer#download"

  ### Analysis
  get 'analysis' => "analysis#analysis"
  get 'analysis/guids' => "analysis#guids"
  get 'analysis/guid/:id' => "analysis#guid"
  get 'analysis/keywords' => "analysis#keywords"
  get 'analysis/vulnerabilities' => "analysis#vulnerabilities"
  get 'analysis/trusted' => "analysis#trusted"
  get 'analysis/similarities' => "analysis#similarities"

  ### Malware/Submit
  get 'submit' => "submit#submit"

  ### AJAX actions
  post 'explorer/actions/:name' => "explorer#actions"
end

web/app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

web/app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        - menu_items.each do | link |
          %li= link_to link[0], link[1]

web/app/views/layouts/_navigation_links.html.haml
%li= link_to 'About', page_path('about')
%li= link_to 'Explorer', explorer_path
%li= link_to 'Analysis', analysis_path
%li= link_to 'Submit', submit_path

web/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Rails Bootstrap'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Rails Bootstrap'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = stylesheet_link_tag "overrides", "darkstrap", media: "all"
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

    = content_for(:javascript)